<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Make Hilbert Curve}
-->

Make Hilbert Curve
========================================

**Author**: Zuguang Gu ( z.gu@dkfz.de )

**Date**: `r Sys.Date()`

-------------------------------------------------------------

```{r, echo = FALSE, message = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    fig.align = "center")
options(markdown.HTML.stylesheet = "custom.css")

options(width = 100)
```

```{r}
suppressPackageStartupMessages(library(HilbertCurve))
set.seed(123)
```

```{r, fig.width = 12, fig.height = 3}
grid.newpage()
pushViewport(viewport(layout = grid.layout(nr = 1, nc = 4)))
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1))
HilbertCurve(1, 100, level = 2, reference = TRUE, newpage = FALSE)
grid.text("level = 2", gp = gpar(col = "red"))
upViewport()
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 2))
HilbertCurve(1, 100, level = 3, reference = TRUE, newpage = FALSE)
grid.text("level = 3", gp = gpar(col = "red"))
upViewport()
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 3))
HilbertCurve(1, 100, level = 4, reference = TRUE, newpage = FALSE)
grid.text("level = 4", gp = gpar(col = "red"))
upViewport()
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 4))
HilbertCurve(1, 100, level = 5, newpage = FALSE)
grid.text("level = 5", gp = gpar(col = "red"))
upViewport()
upViewport()
```

```{r}
x = sort(sample(100, 20))
s = x[1:10*2 - 1]
e = x[1:10*2]
ir = IRanges(s, e)

hc = HilbertCurve(1, 100, level = 4, reference = TRUE)
hc_points(hc, ir)

hc = HilbertCurve(1, 100, level = 4, reference = TRUE)
hc_points(hc, ir, shape = "star")

hc = HilbertCurve(1, 100, level = 4, reference = TRUE)
hc_segments(hc, ir)

hc = HilbertCurve(1, 100, level = 4, reference = TRUE)
hc_rect(hc, ir)

hc = HilbertCurve(1, 100, level = 4, reference = TRUE)
hc_text(hc, ir, sample(letters, length(ir), replace = TRUE))
```

```{r}
col = rainbow(100)
hc = HilbertCurve(1, 100, level = 5)
ir = IRanges(start = 1:99, end = 2:100)
hc_points(hc, ir, gp = gpar(col = col, fill = col))
```

```{r, custom_plot = TRUE, fig.ext = 'png'}
hc = HilbertCurve(1, 100, level = 5, mode = "pixel")
hc_layer(hc, ir)
hc_save(hc, file = fig_path('.png'))
```

```{r}
load(paste0(system.file("extdata", package = "HilbertCurve"), "/refseq_chr1.RData"))
hc = HilbertCurve(1, 249250621, level = 5)
hc_segments(hc, IRanges(start = 1, end = 249250621), gp = gpar(col = "grey"))
hc_segments(hc, ranges(g), gp = gpar(lwd = unit(6, "mm")))
```

```{r}
load(paste0(system.file("extdata", package = "HilbertCurve"), "/mouse_net.RData"))
hc = HilbertCurve(1, 249250621, level = 6, background = "yellow")
hc_points(hc, ranges(mouse), gp = gpar(col = "red", fill = "red"))

load(paste0(system.file("extdata", package = "HilbertCurve"), "/zebrafish_net.RData"))
hc = HilbertCurve(1, 249250621, level = 6, background = "yellow")
hc_points(hc, ranges(zebrafish), gp = gpar(col = "red", fill = "red"))
```



## Session info

```{r}
sessionInfo()
```
