# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hilbert_curve_cpp <- function(level, type = 1L) {
    .Call(`_HilbertCurve_hilbert_curve_cpp`, level, type)
}

